### PR TITLE
Updating span.hpp, to account for new CXX17 and 20

### PR DESCRIPTION
**Pull request by kronos30**
This PR, updates the utils/span.hpp file so that it can account for C++ 17 and 20 respectively for support on Jammy.

### CODE REVIEW

**Review by garyservin — APPROVED** [review]

**Comment by ayrton04** [comment]
Did we pull this in from upstream, or edit it ourselves?

**Review by ayrton04 — APPROVED** [review]

**Comment by kronos30** [comment]
> Did we pull this in from upstream, or edit it ourselves?

@ayrton04 it was pulled from here: https://github.com/martinmoene/span-lite/tree/master/include/nonstd.

Guessing, I should include the URL in the file as a comment?

**Comment by ayrton04** [comment]
> > Did we pull this in from upstream, or edit it ourselves?
> 
> @ayrton04 it was pulled from here: https://github.com/martinmoene/span-lite/tree/master/include/nonstd.
> 
> Guessing, I should include the URL in the file as a comment?

Seems like a reasonable approach.

**Comment by kronos30** [comment]
> > > Did we pull this in from upstream, or edit it ourselves?
> > 
> > 
> > @ayrton04 it was pulled from here: https://github.com/martinmoene/span-lite/tree/master/include/nonstd.
> > Guessing, I should include the URL in the file as a comment?
> 
> Seems like a reasonable approach.

Actually the span.hpp file has the reference within it already. So we should be good.

**Pull request merged**
